version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - ./:/client
      - /client/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./backend
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '5000:5000'
    volumes:
      - ./:/server
      - /server/node_modules
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
